# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v0.2.0
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
advanced: false
github_repo: hextra_patterns
github_user: MEEPofFaith
gradle_deps_type: gradle.properties
gradle_hex_version_key: hexcasting_version
gradle_mod_version_key: mod_version
main_branch: main
minecraft_version: 1.20.1
minecraft_version_in_mod_version: false
mod_description: Random pattern ideas that come to my head. Mostly utility.
mod_display_name: Hextra Patterns
modid: hextra_patterns
multiloader: false
pattern_registry_path: main/java/com/meepoffaith/hextra/init/Patterns.java
